### ISSUE TITLE
PHP's default padding makes RSA vulnerable to padding oracle attacks

### ISSUE THREAD

**Issue by paragonie-scott** [UseMuffin/Crypt#1]
https://github.com/UseMuffin/Crypt/blob/006e48ed46bf9c6bb2b50e5caa5c9dfa3068cdaf/src/functions.php#L34

Reference material:
- http://www.daemonology.net/blog/2009-06-11-cryptographic-right-answers.html
- http://framework.zend.com/security/advisory/ZF2015-10 (same vulnerability in Zend Framework)
- http://cryptopals.com/sets/6/challenges/47/

Take a close look at what https://github.com/paragonie/EasyRSA does. :)

**Comment by jadb** [comment]
Thanks! It's me again, before promoting it I thought of pinging you folks to make sure I don't encourage people using a vulnerable library, so thanks!!!

I will do some reading now and more work :smile:

**Comment by paragonie-scott** [comment]
Thank you for being responsible! :D

The quick fix is to specify the padding mode (`OPENSSL_PKCS1_OAEP_PADDING`) in both operations. Then you'll be roughly on-par with Zend\Crypt's RSA implementation.

**Comment by jadb** [comment]
Will do, but reading just to educate myself ;)

Thanks again, you guys rock!!

**Comment by jadb** [comment]
@paragonie-scott I accidently used _closes_ instead of _refs_. Better now?

I also took the freedom of implementing [a strategy that uses EasyRSA](https://github.com/UseMuffin/Crypt/blob/easyrsa-strategy/src/Model/Behavior/Strategy/EasyRSAStrategy.php) for people to use if they want to require phpseclib, etc.

Let me know of any other comments and thanks again!

**Comment by paragonie-scott** [comment]
This has been fixed, so I'm closing it. :)

**Comment by jadb** [comment]
:+1:  Thanks for helping!
